obj-$(CONFIG_AW_AXP81X) += axp81x-board.o
obj-$(CONFIG_AW_AXP81X) += axp81x-board-device.o
obj-$(CONFIG_AW_AXP81X) += axp81x-regu.o
obj-$(CONFIG_AW_AXP81X) += axp81x-sply.o
obj-$(CONFIG_AW_AXP81X) += virtual81x.o
obj-$(CONFIG_AW_AXP81X) += virtual81x_dev.o
obj-$(CONFIG_AW_AXP81X) += axp81x-init.o
