obj-$(CONFIG_AW_AXP20) += axp20-board.o
obj-$(CONFIG_AW_AXP20) += axp20-init.o
obj-$(CONFIG_AW_AXP20) += axp20-regu.o
obj-$(CONFIG_AW_AXP20_OCV) += axp20-sply.o
obj-$(CONFIG_AW_AXP20_COU) += axp20-sply-cou.o
obj-$(CONFIG_AW_AXP20_OCV_SMALL) += axp20-sply-modify.o
obj-$(CONFIG_AW_AXP20) += virtual20.o
obj-$(CONFIG_AW_AXP20) += virtual20_dev.o
